### ISSUE TITLE
U+06C0 omitted from Persian Character Usage page

### ISSUE THREAD

**Issue by KentSpiel** [r12a/app-charuse#11]
U+06C0 ARABIC LETTER HEH WITH YEH ABOVE is listed as  proper character for Persian here: https://r12a.github.io/scripts/arabic/block#char06C0 — but does not appear here: https://r12a.github.io/app-charuse/?language=pes.
I have a text that uses this character frequently so am surprised this is not listed.

**Comment by r12a** [comment]
thanks for pointing that out, @KentSpiel.  Initial thoughts are that, despite the fact that Wikipedia claims that it is used, i think that the Persian block link is incorrect to list this as a Persian letter.  I believe it's intended for use with other languages, such as Uighur.   Note that it only joins to the right, and that it decomposes to ە U+06D5 ARABIC LETTER AE, rather than ه U+0647 ARABIC LETTER HEH.  Also, the Unicode Standard description file says "• for ezafe, use 0654 over the language-appropriate base letter".

There are many Arabic script characters that look the same, and often are separated only by subtle differences. Unless i find evidence to the contrary, i think this is one such.

I never did get around to properly documenting Persian usage, but i think i'll give that a go now.  In the meantime i'll remove the entry from the block page.

Btw, what text are you referring to when you say you see it in use?

**Comment by KentSpiel** [comment]
Hi Richard, thanks for getting back to me two years ago.  As the Biblica Translation Technology Director one of my jobs is to insure the technical correctness of our translations.  This issue came up when I was checking our  Persian Contemporary Bible 2022, an open license version of which is available here https://open.bible/bibles/persian_iranian-biblica-text-bible/ 
After examining the Bible text I found 1824 instances of U+06C0,  always at the end of a word, and 6657 instances of the combination U+0647 followed by U+0654 again always at the end of a word. I did a word check and found 418 word pairs that differed only by the final letter  هٔ/ۀ This is obviously an error that needs to be corrected. I wish I had processed your answer sooner.
Based on this I think we can conclude that your analysis is correct, or at least that this does not provide any evidence to the contrary.
